# Generated by Django 2.2.5 on 2020-11-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
