# Generated by Django 2.2.5 on 2020-11-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0002_post_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='remarks',
        ),
    ]
