# Generated by Django 2.2.5 on 2020-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0003_remove_post_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
