# Generated by Django 2.2.5 on 2020-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0004_post_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300, unique=True)),
                ('lastname', models.TextField()),
                ('remarks', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
