# Generated by Django 2.2.5 on 2020-11-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0005_auto_20201109_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
