# Generated by Django 2.2.5 on 2020-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0007_auto_20201110_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='example',
        ),
    ]
