# Generated by Django 2.2.5 on 2020-11-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylabz', '0008_auto_20201110_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
    ]
